kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: eksrds.cawkdymmg1qt.us-west-2.rds.amazonaws.com
  ports:
  - port: 3306
    targetPort: 3306
    name: dbport