apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: user-mgmt
spec:
  type: NodePort
  selector:
    app: user-mgmt
  ports:
    - port: 8095 # define port of nodeport service
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8095
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 32100