apiVersion: v1
kind: Service
metadata:
  name: usermgmt-nodeport-svc
  labels:
    app: user-mgmt
spec:
  type: NodePort
  selector:
    app: user-mgmt
  ports:
    - port: 80  # nodeport service port
      targetPort: 8095 # port of pod
      nodePort: 32100  # port of ec2 node