apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: my_app
    type: ui
spec:
  kind: NodePort
  ports:
  - targetPort: 80
    nodePort: 30008
    port: 80
  selector:
    app: my_app
    type: ui