apiVersion: v1
kind: ReplicationController
metadata:
  name: bipro-rc
  lebels:
    app: bipro-app
    type: UI
spec:
  - template:
      metadata:
        name: bipro-pod
        lebels:
          app: bipro-app
          type: UI
      spec:
        containers:
        - name: nginx-controller
          image: nginx
replicas: 2
selectors:
  matchlabels:
    type: UI
