apiVersion: v1
kind: ReplicationController
metadata:
  name: bipro-rc
  lebels:
    app: my_app
    type: ui
spec:
  - template:
      metadata:
        name: bipro-pod
        lebels:
          app: my_app
          type: ui
      spec:
        containers:
        - name: nginx-controller
          image: nginx:latest
replicas: 2
selectors:
  matchlabels:
    app: my_app
    type: ui
