apiVersion: v1
kind: Service
metadata:
  name: clb-svc
  labels:
    app: user-mgmt
spec:
  type: LoadBalancer
  selector:
    app: user-mgmt
  ports:
    - port: 80 # define port of loadbalancer Listener
      targetPort: 8095
      nodePort: 32100